version: '3.8'

services:
  mraprguildbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mraprguildbot
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=production
      - PORT=5000
      - HOST=0.0.0.0
      - BOT_NAME=@mraprguildbot
      - LOG_LEVEL=INFO
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge